### ISSUE TITLE
Add comments feature to the blog

### ISSUE THREAD

**Issue by user-take** [TruncatedDinosour/blog.ari-web.xyz#2]
https://utteranc.es/

**Comment by user-take** [comment]
Try these

1. Enable Github Discussions from the repository settings main page
2. Install this app to this repository https://github.com/apps/giscus
3. Add this code under scripts/blog/BLOG_HTML_TEMPLATE after line 122
```html
<script src="https://giscus.app/client.js"
        data-repo="TruncatedDinosour/blog.ari-web.xyz"
        data-repo-id="R_kgDOHzHLWw"
        data-category="General"
        data-category-id="DIC_kwDOHzHLW84CQu6E"
        data-mapping="pathname"
        data-strict="0"
        data-reactions-enabled="1"
        data-emit-metadata="0"
        data-input-position="bottom"
        data-theme="dark"
        data-lang="en"
        crossorigin="anonymous"
        async>
    </script>
```

utteranc.es doesn't work for some reason because it doesn't size the height of the iframe automatically. (I tried it and wasted 1 hours)

**Comment by TruncatedDinosour** [comment]
https://usere.ari-web.xyz/

**Comment by TruncatedDinosour** [comment]
(I like bad issue titles kinda)
